### PR TITLE
Added support for custom AuthenticationMechanism

### PR DESCRIPTION
**Pull request by munjalii**
I wanted to achieve support for custom token for Identity, did not find it in current codebase. To achieve same added custom AuthenticationMechanism.

### CODE REVIEW

**Comment by mkjsix** [comment]
Thank you @munjalii, we're going to review your PR shortly.

**Comment by pmukherjeee** [comment]
Update?

**Comment by ujibang** [comment]
started reviewing now. Will take few days...it misses tests and documentation...

**Comment by ujibang** [comment]
I merged this with few modifications. Check it out on master. I also added an example authentication mechanism: org.restheart.security.impl.IdentityAuthenticationManagerFactory

refer to comments in configuration file and check the example auth mech factory to see how to use this

**Comment by munjal-gc** [comment]
Any plan to include this enhancement to upcoming 3.1.x Release? Just used 3.1.3 release version for new project but realised that changes are there in master but not present in 3.1.x branch...

**Comment by mkjsix** [comment]
@ujibang I think this should go into 3.2 instead of 3.1

**Comment by munjal-gc** [comment]
What is potential timeline of first 3.2 release, also this enhancement does not break any backward compatibility in 3.1.x, so it would be great if can be considered for 3.1.x as well...

**Pull request merged**
