### PR TITLE
provide prometheus metrics per database and collection using labels

### PR DESCRIPTION
**Pull request by christiangroth**
I've changed the way prometheus metrics are returned, only if queried via /_metrics. In this case the metrics contain all gathered values including database and collection labels. This allows to create e.g. grafana dashboards on database and/or collection level using a single metrics endpoint only. The JSON metrics format hasn't changed at all!

### CODE REVIEW

**Comment by lenalebt** [comment]
I had a look at the code with him together and do not see any major problems, especially not anything that would break the existing behaviour.

**Comment by mkjsix** [comment]
Hi @christiangroth , @lenalebt 
Do you mind editing a bit the metrics documentation page, to briefly explain what's new and review if something is obsolete? Please highlight additions under a "what's new in 3.9" so other people won't try to use new features with older releases. You can edit open a PR on https://restheart.org/learn/requests-metrics/
Thank you!

**Comment by christiangroth** [comment]
Yes, I will take a look at the documentation!

**Comment by mkjsix** [comment]
Thank you @christiangroth 
We're planning to release 3.9 within the end of this week, I need to check with @ujibang if we need to include something more.

**Comment by christiangroth** [comment]
Sounds great! It's very likley that we'll upgrade quickly.

**Pull request merged**
