### PR TITLE
fixes #293: prometheus metrics handler to not contain non-numeric values

### LINKED ISSUE #293: Prometheus Integration
I tried to plug Prometheus to monitoring my RestHeart API but I'm getting a parse error:

```
level=warn ts=2018-06-21T21:12:52.174717536Z caller=scrape.go:713 component="scrape manager" scrape_pool="General RestHeart" target=http://xx.xx.xx.xx:80/google/_metrics msg="append failed" err="strconv.ParseFloat: parsing \"milliseconds\": invalid syntax"
```

Does anyone know how can I fix it?

Thanks guys!

### PR DESCRIPTION
**Pull request by lenalebt**

### CODE REVIEW

**Comment by lenalebt** [comment]
I don't know how to update the docs accordingly. I'd need to simply remove all the lines containing "unit".

**Comment by mkjsix** [comment]
@lenalebt you can edit the docs at  https://restheart.org/learn/requests-metrics/ by opening a PR on

https://github.com/SoftInstigate/restheart-website/edit/gh-pages/learn/requests-metrics.md

If you can't do that let us know and we'll do it, thank you.

**Comment by mkjsix** [comment]
@lenalebt let us edit the docs, it's easier...

**Comment by mkjsix** [comment]
@lenalebt for example, I've found these:

```
http_response_timers_DOCUMENT_duration_units{method="GET",code="4xx"} milliseconds 1510039263986
http_response_timers_DOCUMENT_rate_units{method="GET",code="4xx"} calls/second 1510039263986
```
and
```
      "duration_units": "milliseconds",
      "rate_units": "calls/second"
```

Should I delete all of them?

**Comment by lenalebt** [comment]
No, please only delete the ones in the prometheus version. It will stay for JSON.

**Comment by mkjsix** [comment]
Done, thanks @lenalebt

**Comment by mkjsix** [comment]
Besides 3.4.0-SNAPSHOT, this fix is now available in stable release RESTHeart [3.3.7](https://github.com/SoftInstigate/restheart/releases/tag/3.3.7).

As usual, Docker images are available [here](https://hub.docker.com/r/softinstigate/restheart/tags/).

**Pull request merged**
