### PR TITLE
Escaping quotes in prometheus metrics.

### PR DESCRIPTION
**Pull request by christiangroth**
See issue #379

### CODE REVIEW

**Comment by christiangroth** [comment]
Not sure why integration tests fail. Is this a common issue or is this caused by my changes??

**Comment by mkjsix** [comment]
Hi @christiangroth we are changing so many things is RESTHeart master branch right now that we still have to fix integration tests, so it's likely that you commit has nothing to do with this problem. We're actively working on fixing them.

**Comment by mkjsix** [comment]
I have forced the merge of this PR and cherry-picking it into a new 4.1.x branch from which we'll package a new release

**Comment by mkjsix** [comment]
Hi @christiangroth 

After copying your commit into a new branch the build is still in error. You can run a `mvn clean package`

```
Tests in error: 
testDatabaseAndCollectionNamesEscapedCorrectly(org.restheart.handlers.metrics.MetricsHandlerResponseTypePrometheusTest)
```

See: https://travis-ci.org/github/SoftInstigate/restheart/jobs/661584727

Please add you fixes into branch `4.1.x` instead of `master`

https://github.com/SoftInstigate/restheart/tree/4.1.x

**Comment by mkjsix** [comment]
Hi @christiangroth 

After copying your commit into a new branch the build is still in error:

```
Tests in error: 
testDatabaseAndCollectionNamesEscapedCorrectly(org.restheart.handlers.metrics.MetricsHandlerResponseTypePrometheusTest)
```

See: https://travis-ci.org/github/SoftInstigate/restheart/jobs/661584727

Note that this test seems not to be a unit test but an integration test. In fact, I see the below error:

```
testDatabaseAndCollectionNamesEscapedCorrectly(org.restheart.handlers.metrics.MetricsHandlerResponseTypePrometheusTest)  Time elapsed: 0.011 sec  <<< ERROR!
java.lang.ExceptionInInitializerError
	at org.restheart.db.MongoDBClientSingleton.getInstance(MongoDBClientSingleton.java:57)
	at org.restheart.db.DatabaseImpl.<init>(DatabaseImpl.java:69)
	at org.restheart.handlers.PipedHttpHandler.<init>(PipedHttpHandler.java:46)
	at org.restheart.handlers.metrics.MetricsHandler.<init>(MetricsHandler.java:72)
	at org.restheart.handlers.metrics.MetricsHandlerResponseTypePrometheusTest.testDatabaseAndCollectionNamesEscapedCorrectly(MetricsHandlerResponseTypePrometheusTest.java:161)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.IllegalStateException: not initialized
	at org.restheart.db.MongoDBClientSingleton.<init>(MongoDBClientSingleton.java:85)
	at org.restheart.db.MongoDBClientSingleton$MongoDBClientSingletonHolder.<clinit>(MongoDBClientSingleton.java:156)
	... 35 more
```

Integration tests must be in a class ending with IT postfix and belonging to the package `org.restheart.test.integration`

Please add you fixes into branch `4.1.x` instead of `master`

https://github.com/SoftInstigate/restheart/tree/4.1.x

**Pull request merged**
