### PR TITLE
fixed initialization of MetricsHandler in test

### PR DESCRIPTION
**Pull request by christiangroth**
Fixed the test introduced with PR #380 for issue #379

### CODE REVIEW

**Comment by christiangroth** [comment]
At least the mvn clean package works now, hope this is all that was missing.

**Comment by mkjsix** [comment]
Thanks @christiangroth,
Do you need also to patch restheart-security? In this case I'll revoke temporarily the archiviation of that project so that you could open a PR. Otherwise I'm going straight to create a new release of all projects and platform.

**Comment by mkjsix** [comment]
@christiangroth I talked to @ujibang who remembered me that this handler is not present in restheart-security, so nothing to do on your side.

**Comment by christiangroth** [comment]
Great thank you. We will wait for the fix of logging trace headers in RH security and then hopefully update soon to the latest platform releases.

**Pull request merged**
