### PR TITLE
Resources should be closed

### PR DESCRIPTION
**Pull request by AymanDF**
This pull request is focused on resolving occurrences of Sonar rule squid:S2095 - “ Resources should be closed”. You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S2095
Please let me know if you have any questions.
Ayman Abdelghany.

### CODE REVIEW

**Comment by ujibang** [comment]
hi @AymanDF 

make sure to run the integration test before sending pull requests. 

```
mvn verify -DskipITs=false
```

as soon as if you confirm it passes the ITs, I'll accept the PR

Thanks

**Comment by mkjsix** [comment]
Meanwhile I'm having a look at configuring Travis-CI to automatically start mongodb and run the ITs, it's on my todo list since a lot of time. This way the PR will automatically trigger the integration tests.

**Comment by mkjsix** [comment]
@AymanDF @ujibang the Travis-CI build now always executes all integration tests against a MongoDB 3.2 instance, so each pull request is verified automatically, upfront.

**Comment by mkjsix** [comment]
@AymanDF I had to revert this merge because it's breaking the build: the integration tests fail.
You can have a look at the failed build at: https://travis-ci.org/SoftInstigate/restheart/builds/108181784

Please fix the code and run the `mvn verify -DskipITs=false` before opening the PR again.

Thank you!

**Pull request merged**
