### PR TITLE
This commit has a couple of changes: \n 1. Provide our own implementa…

### PR DESCRIPTION
**Pull request by mohankv**
…tion of AuthTokenAuthenticationMechanism and AuthTokenInjecterHandler. \n 2. To have a custom implementation of AccessManager and/or DbIdeDbIdentityManager in a custom package (say, package com.<company> security.impl;)

### CODE REVIEW

**Comment by ujibang** [comment]
Hi @mohankv, thanks for the PR; it provides a significant improvement to the RESTHeart security model.

Is it going to address this [issue](https://github.com/SoftInstigate/restheart/issues/135) in your opinion?

Before merging it and since it relates to security, I need you to provide some information to be added to the [documentation security section ](https://softinstigate.atlassian.net/wiki/x/W4CM):

- In [Enable and Configure Security](https://softinstigate.atlassian.net/wiki/x/IgDM) you need to explain why and how to configure the _AuthTokenAuthenticationMechanism_ and _AuthTokenInjecterHandler_ 
- you need to add two new pages _Custom Authentication Manager_ and _Custom Auth Token Injecter_  that follows the existing [Custom Identity Manager](https://softinstigate.atlassian.net/wiki/x/HADM) and [Custom Access Manager](https://softinstigate.atlassian.net/wiki/x/HgDM) pages, i.e. explain how to implement custom code and provide a working example.

If you are fine with this, I can provide you write access to our confluence wiki...

**Comment by mkjsix** [comment]
Hi @mohankv,
Thank you for this PR. As Andrea wrote, some documentation would be perfect, as the subject is complex for newcomers. If you want you could just send us some raw text and we'll bother to put that into our Confluence in a better form, if this could save you some time.

**Comment by mohankv** [comment]
Thanks @ujibang and @mkjsix.

Sure I will provide documentation sometime next week.

**Comment by mohankv** [comment]
There is a better way to achieve this. I am working on to refactor the solution that makes it simpler and better. I will submit a new merge request shortly.

**Comment by ujibang** [comment]
ok thanks

look forward for your new PR!

**Comment by Mich-b** [comment]
Any update regarding this? It is hard to find a real-life use case for restheart without a proper token-based authN/authZ mechanism IMO.

**Comment by ujibang** [comment]
Hi @mohankv any news about this? Can you support @Mich-b with his question?

thanks

**Pull request closed without merging**
