### PR TITLE
add time limit config option for queries

### PR DESCRIPTION
**Pull request by simkoviktor**
I've needed an option to kill the long running queries on the server, so I've added a time limit option.
This time limit applies to queries, aggregation pipelines and Map-Reduces.

### CODE REVIEW

**Comment by ujibang** [comment]
Hi I looked at this pr, well done.

I think that setting the time limit in the MongoDbSingleton can be avoided. You can get the Configuration via Bootstrapped.getConfiguration() method

**Comment by simkoviktor** [comment]
Hello!

Thank you!
I've changed it to use Bootstrapper.getConfiguration().
I've been looking for a solution to get the configuration, but somehow this method has escaped my attention.

**Comment by ujibang** [comment]
hello @simkoviktor 

another point is, what is the response code in case of timeout?

it would be fantastic to return 408 Request Timeout in case the request time exceeds the limit. 

Is that possible? does timeLimit() throws an exception in case?

**Comment by simkoviktor** [comment]
Now it returns the following response: 

```
{
    "http status code": 500,
    "http status description": "Internal Server Error",
    "message": "exception: operation exceeded time limit"
}
```
Yes I think returning 408 Request Timeout is possible. 
maxTime throws a `MongoExecutionTimeoutException`.

**Comment by simkoviktor** [comment]
I've added a handler for it,
Now it returns:

```
{
    "http status code": 408,
    "http status description": "Request Timeout",
    "message": "Operation exceeded time limit"
}
```

**Comment by simkoviktor** [comment]
What do you think, wouldn't it be better to have two separate time limits?
One for the queries, and another for the aggregations.
Or is this single one ok for both?

**Comment by ujibang** [comment]
I think that it makes sense to have two parameters. Aggregations might require more time than usual queries....

**Comment by simkoviktor** [comment]
Ok, I've separated the time limits.

**Pull request merged**
