### PR TITLE
Added ADIdentityManager.java for ActiveDirectory/LDAP authentication

### PR DESCRIPTION
**Pull request by jbrownD3**

### CODE REVIEW

**Comment by mkjsix** [comment]
Hi @jbrownD3 , thank you for this contribution.
We don't have much experience with AD but I think it doesn't harms to accept this PR and let you or others to improve this in the future. It would be very nice if you could contribute further in terms of adding a piece of official documentation or by writing a blog post, etc, whenever you have time.

**Comment by mkjsix** [comment]
@ujibang you should have a look and decide for merging

**Comment by mkjsix** [comment]
Hi @ujibang 
I merged this PR, please pull.

**Comment by jbrownD3** [comment]
@mkjsix I would be happy to write something up, can you point me to where I should go to do that?

**Comment by mkjsix** [comment]
Hello @jbrownD3 
Thank you, that would be very useful. I've created a Confluence page for this: https://softinstigate.atlassian.net/wiki/x/AoCIAg
You could send us an email to info@softinstigate.com so that we can activate your editing permissions.

**Pull request merged**
