### PR TITLE
Refactor Prometheus metrics to a single timeseries allowing easier aggregation

### PR DESCRIPTION
**Pull request by christiangroth**
Hi,

I've refactored the prometheus metrics generation to produce a single timeseries only. This allows easiert aggregation in Grafana or similar, because now you can use the aggregation functions from prometheus query language itself and you don't have to rely on functionality in Grafana or other tools.

We had the problem aggregating (sum) the count of requests per response type, because grafana does not create the sum if not all timeserien are present. So if no request for files/assets was made, no metrics are displayed resulting in useless dashboards.

### CODE REVIEW

**Comment by mkjsix** [comment]
Thank you @christiangroth ,

I'd love to read an opinion from @lenalebt before merging this.

**Comment by lenalebt** [comment]
Thanks!

**Comment by christiangroth** [comment]
Perfect, thanks!

**Comment by christiangroth** [comment]
Hi @mkjsix , I'm wondering when the next release will be made. Do you have any plan according the next release date? Thanks, Christian

**Comment by christiangroth** [comment]
@mkjsix that's totally fine! I just wanted to know if it takes some days or maybe a week or even several weeks.

**Comment by mkjsix** [comment]
Hi @christiangroth 
We have just released [RESTHeart 3.5.0](https://github.com/SoftInstigate/restheart/releases/tag/3.5.0).

**Pull request merged**
