### PR TITLE
Dropwizard metrics support

### LINKED ISSUE #249: Support for metrics using dropwizard.io tooling
Hi together,
we're interested in some metrics from restheart (response times etc) for autoscaling in k8s. I already have seen that there is a ticket in your backlog in Jira (https://softinstigate.atlassian.net/browse/RH-23). Do you already have plans to implement that? If not, I'd volunteer for an implementation and create a PR, if that is fine for you.

### PR DESCRIPTION
**Pull request by lenalebt**
This pull-request will close #249 .

It adds support for metrics to restheart and behaves as follows:

There are a few new endpoints:
* `/_metrics`
* `/$DBNAME/_metrics`
* `/$DBNAME/$COLLECTIONNAME/_metrics`.

You can query them to get metrics information; each upper level contains all the information from the lower levels, aggregated. There are two output formats: classic dropwizard metrics JSON format (see https://github.com/iZettle/dropwizard-metrics/blob/master/metrics-json/src/main/java/io/dropwizard/metrics/json/MetricsModule.java for the format) and Prometheus (see https://prometheus.io/docs/instrumenting/exposition_formats/).

Prometheus is the default format and will be selected if you do not specify anything. This allows easier integration into a k8s stack (e.g. for auto-scaling by response time).
For the JSON format, there are 2 options: Use the `rep` query parameter set to `PJ` or `PLAIN_JSON` (as you know it from classic restheart), or use HTTP content negotiation using `Accept` headers (see https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1). If you give both, the query parameter wins.

Whether restheart will collect metrics at all depends on the `metrics-gathering-level` defined in the config file (default is `ROOT`). You can set it to `OFF`, `ROOT`, `DATABASE` or `COLLECTION`, which will in turn collect from least to most metrics. If metrics do not get gathered at a given level, the answer from the respective endpoint will be `404 NOT FOUND`.

If I should make changes to the current implementation, tell me, I am open for suggestions :).

### CODE REVIEW

**Comment by ujibang** [comment]
Thanks @lenalebt, that's great!

**Comment by ujibang** [comment]
@lenalebt 

would you write a documentation page about this? It should go here https://softinstigate.atlassian.net/wiki/x/HAALBw

If you have time I'll give you permission to confluence.

Thanks

**Comment by mkjsix** [comment]
Great job! Meanwhile I'm adding the above comments to the release notes for v3.2.

**Comment by lenalebt** [comment]
@ujibang I am fine writing some docs as well. However, I might not find time this week. I'll come back to you!

**Comment by mkjsix** [comment]
We have published a pre-release [3.2.0-beta-1](https://github.com/SoftInstigate/restheart/releases/tag/3.2.0-beta-1) including this PR.

As usual, also available as a docker image:

`docker pull softinstigate/restheart:3.2.0-beta-1`

**Comment by lenalebt** [comment]
Illness put this back a little more. Sorry for that! I could write docs starting from today, just need access to the confluence...

**Comment by mkjsix** [comment]
Hi @lenalebt 
We gave you access to Confluence, you can edit this page: https://softinstigate.atlassian.net/wiki/x/HAALBw
Please let us know if you have any problem.

**Comment by lenalebt** [comment]
Now I have read access to the page, but I cannot edit it. Can you give me access?

Meanwhile, I'll write the docs as a comment in the confluence.

**Comment by lenalebt** [comment]
Works now, thank you!

**Pull request merged**
